{{ if .Values.istio.enabled }}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: oathkeeper-passthrough
  namespace: kcp-system
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            principals:
              - "cluster.local/ns/kyma-system/sa/oathkeeper-maester-account"
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: istio-kubeconfig
  namespace: kcp-system
spec:
  action: ALLOW
  rules:
    - from:
        - source:
            namespaces:
              - istio-system
      to:
        - operation:
            methods:
              - GET
            paths:
              - /kubeconfig*
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kyma-env-broker.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
{{ end }}
