apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURERENDQWZTZ0F3SUJBZ0lSQUlPaWt3R1BTb1ZVd05hYUVEd0tKNll3RFFZSktvWklodmNOQVFFTEJRQXcKTHpFdE1Dc0dBMVVFQXhNa05tUTJNREk0Tm1JdE5qUmxOUzAwWlRjNExXRTFPREV0Tm1aa00yVmhORGM1T0RreQpNQjRYRFRFNU1URXhOakExTkRZeE0xb1hEVEkwTVRFeE5EQTJORFl4TTFvd0x6RXRNQ3NHQTFVRUF4TWtObVEyCk1ESTRObUl0TmpSbE5TMDBaVGM0TFdFMU9ERXRObVprTTJWaE5EYzVPRGt5TUlJQklqQU5CZ2txaGtpRzl3MEIKQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBa2dOcjJDZUI2eG1ZMW5hNGRqK0hsUDhZQlV2ZTk1cUc2ZjhXZUZhcAovbHBqY0t2c0hNWEhFaXVja2lWRTYxRW9jcmk2Z2FGVFI1clM3ZXd5V0ViUUdRTDVweEdqa1VBRXVNSSttMkJFCjYxSjA5VUsyMHB6M0F5RlhKOUhGVUZ0Nm9UeFdYQUNvdWYxbVl1RWx5MXJFR3RaMnFJRVdUUHdRWmhISlJlN28KWEZERmlNVlFGUzBDVSswS0w3a2RaWEd1K3FvQ0FDNmMzWi9JK3lZaDNDcTdpZDBpZCtIQWlvazFkUXlyalRkZApjM3hNL0tBcXNzNkQ2STIwUm1tb2taMjV4bE1sUy91Ti9tMTBCeWVHQ0xPaU00eDdBa05yWi9zMDVUTlBnL0JSCkM5dm1FQVZtTTRlNnZ2VEtEbmdHR0t4RVd1RUpaTkZuTXVMaXlUMGcrL243T3dJREFRQUJveU13SVRBT0JnTlYKSFE4QkFmOEVCQU1DQWdRd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DQVFFQQpJbVdZSk9STlpsOXM4NzlWMUh3ZDE2a2lnQVgzNWNrekVocWFOQTN4T1JuVnFUTC9iWWpLY0tjVXRXek5RTGhnCmNQa3YzTXpPdEVhdlVrMEQ3RHBsbFZyQ3BMU3dFcHYrTXFEZElONUlWOGV5eTJOUU9zMUR6MG83aklVSmx4VWcKV3ZOT0RCRHd5MmlhVTd0YXoxUkxBcGNEUWFIeWQ5K1dBU3RSeGFxWlozanJSMGpKaWtyY3hqREZyaHpRaWlqRQpmcUxVWEFuUzdzbmFEZkJuRXcrTC9VLzRZd3RiRUJxTVF4UWpwMk15Uzh3ZWJDV2ZIZTdUeDVJMFlpWWowNzREClN5aDNKYTR4a3VLOHlBZUt2MmNXMzJGQUJBMytlSnhjM1Y3R0wrTmdKZFNaNmI5b2RPTDhVVDdDSzBINzZiL04KQzRFWWIrcnBtSTVOdk5KamhVZ2NRdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://34.76.121.100
  name: gke_sap-ti-dx-kyma-mps-dev_europe-west1_kyma-mps-dev
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1akNDQWM2Z0F3SUJBZ0lRZWRLRkhqU01pY2ZkVVFBWlhlQWxSakFOQmdrcWhraUc5dzBCQVFzRkFEQU4KTVFzd0NRWURWUVFERXdKallUQWVGdzB5TWpBMk1UWXdNakk0TVRGYUZ3MHpNakEyTVRZd01qSTRNVEZhTUEweApDekFKQmdOVkJBTVRBbU5oTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF1b1pNCmxQUmFCNmgrMEJCRWF0VDkwamxqTlBxU0ZHOUNCZWpoY2l2enlEazd6d0dGNEF1Mit2SE0vYzRJb0VnK0dJRncKUjZXdVRNRFRtVlF5SHEzTlhrbFdWMERVR2tUUlMzNktTRUd5bnllMUlxYU5VcnhzRE5reTd3YlpOaGI5eExuVQozcUlCWHoyeGZoN013L1NyQmZwbFBqaFdJbm9mellsbVJxa0xZS3dJMHVQTDVYeFJYWjMwaU5NN1hlVDZxUjN0CjdNS3pwWUNRc2RXdi9Qek9aOENtY0tISXcxV290MFFtL2FpbVVYdXVLWDhMczBnME10cnUrY1J5TTcxZDRFWVUKZ3JRVzdEbWprNTRORDJ6bWpIaG9FcXVkOWdqR1hTNkZoS3ZVZ3hsZ25iNFloWHRFYi9sVGdJQTRHZnl6aVExVgptTkw1RDVCTGdmYWpOUTkzWXdJREFRQUJvMEl3UURBT0JnTlZIUThCQWY4RUJBTUNBYVl3RHdZRFZSMFRBUUgvCkJBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVWJqZHhZeFROck0yK3puVHBKQmJ3SVJRRzUyZ3dEUVlKS29aSWh2Y04KQVFFTEJRQURnZ0VCQUJuYUk5emp2UkViUFRxTmtNYXpqempEUEVLM3RjUHhvVk9RYVh0N1VFck1CK0V2TStmQQpBQXBtYUgvTmEwdnBabkJiMmM3bVdQbk5ZdjVqSnRHV05NYTc0M1RTcEVYNTJaWUZ0ZU5NK2wxa1R2R3BCc2UvClBCZy9rRDZMSTNLaEFKTkYrUHRRN0tvd1J4Z3NjNWsveDRleWtuYzQzUjNoUjNnaFFGbStHL2NBdS9KOUptdXcKVnJnRnpoNXpiaUJKbGljTjJQNkhWWk4wNXo1bnpwS1NHdlExS2l1dGpxbDhyVlhKeW1DUWVPWXZLTWd5ZTNMWApielo1WVg1Zlk0V2hmTHYwOG5YZ015SXdmK004d2RYZXdTZGZwZUhCQW1FNUhoSmVuZGxMcXArUnhDdmRQRWN3CmJINitoN1pQMWpHTFI5blRYME1JQisxVXZ3UEs2eFhTbWdNPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://api.c-0e01896.dev.kyma.ondemand.com
  name: shoot--kyma-dev--c-0e01896
contexts:
- context:
    cluster: gke_sap-ti-dx-kyma-mps-dev_europe-west1_kyma-mps-dev
    user: gke_sap-ti-dx-kyma-mps-dev_europe-west1_kyma-mps-dev
  name: gke_sap-ti-dx-kyma-mps-dev_europe-west1_kyma-mps-dev
- context:
    cluster: shoot--kyma-dev--c-0e01896
    user: shoot--kyma-dev--c-0e01896
  name: shoot--kyma-dev--c-0e01896
current-context: gke_sap-ti-dx-kyma-mps-dev_europe-west1_kyma-mps-dev
kind: Config
preferences: {}
users:
- name: gke_sap-ti-dx-kyma-mps-dev_europe-west1_kyma-mps-dev
  user:
    auth-provider:
      config:
        access-token: ya29.a0ARrdaM-wg4yKWsnApOnvoqy6U9vjhPwoYx8EyTQyl7Ga9pUQNxW7zNUExv0Vtnn_LYEDTNKYc18xiY-C4if_KISeG9bUhnFtPO7SAzc6A5beDN5LKWMSUyvYsV1lCjIBuEatFj-IweT8obGea7cROJXLPfZDUH1iQGTb-g
        cmd-args: config config-helper --format=json
        cmd-path: /Users/i566483/google-cloud-sdk/bin/gcloud
        expiry: "2022-06-21T13:37:48Z"
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
- name: shoot--kyma-dev--c-0e01896
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - --oidc-issuer-url=https://kymatest.accounts400.ondemand.com
      - --oidc-client-id=9bd05ed7-a930-44e6-8c79-e6defeb7dec9
      - --oidc-extra-scope=email
      - --oidc-extra-scope=openid
      command: kubectl-oidc_login
      env: null
      installHint: |
        kubelogin plugin is required to proceed with authentication
        # Homebrew (macOS and Linux)
        brew install int128/kubelogin/kubelogin

        # Krew (macOS, Linux, Windows and ARM)
        kubectl krew install oidc-login

        # Chocolatey (Windows)
        choco install kubelogin
      interactiveMode: IfAvailable
      provideClusterInfo: false
